# Generated by Django 6.0.3 on 2026-04-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessorassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='question_id',
            field=models.CharField(max_length=32),
        ),
    ]
