# Generated by Django 6.0.3 on 2026-04-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assessor_sectors',
            field=models.ManyToManyField(blank=True, related_name='assigned_assessors', to='sectors.sector'),
        ),
    ]
