export const BASIC_QUESTIONS = [
  {
    id: 1,
    type: 'basic',
    text: 'Your Primary Industry',
    options: [
      { text: 'Textile' },
      { text: 'Pharmaceutical' },
      { text: 'Chemicals' },
      { text: 'Wire & Cable' },
      { text: 'Engineering Goods' },
      { text: 'Plastic & Packaging' },
      { text: 'N/A', isNA: true },
    ],
  },
  {
    id: 2,
    type: 'basic',
    text: 'Company Turnover (INR)',
    options: [
      { text: '< 100 Cr' },
      { text: '< 500 Cr' },
      { text: '< 1000 Cr' },
      { text: '< 5000 Cr' },
      { text: '> 5000 Cr' },
      { text: 'N/A', isNA: true },
    ],
  },
  {
    id: 3,
    type: 'basic',
    text: 'Number of Employees',
    options: [
      { text: '< 50' },
      { text: '< 100' },
      { text: '< 500' },
      { text: '< 1000' },
      { text: '> 1000' },
      { text: 'N/A', isNA: true },
    ],
  },
  {
    id: 4,
    type: 'basic',
    text: 'What are your primary business objective in next 2-3 years? (Multiple selection is allowed)',
    options: [
      { text: 'Reduce Cost of Poor Quality' },
      { text: 'Reduce Inventory Levels' },
      { text: 'Reduce Product Time-to-Market' },
      { text: 'Improve Market Share/Revenue' },
      { text: 'Improve Customer Satisfaction' },
      { text: 'N/A', isNA: true },
    ],
  },
  {
    id: 5,
    type: 'basic',
    text: 'Number of Factory location',
    options: [
      { text: '1' },
      { text: '2-5' },
      { text: '6-10' },
      { text: '10+' },
      { text: 'Global Presence' },
      { text: 'N/A', isNA: true },
    ],
  },
  {
    id: 6,
    type: 'basic',
    text: 'What are your customer channels?',
    options: [
      { text: 'B2B' },
      { text: 'B2B & B2C' },
      { text: 'B2C' },
      { text: 'N/A', isNA: true },
    ],
  },
  {
    id: 7,
    type: 'basic',
    text: 'Which Markets do you operate in currently?',
    options: [
      { text: 'India' },
      { text: 'India & Export' },
      { text: 'Export' },
      { text: 'N/A', isNA: true },
    ],
  },
  {
    id: 8,
    type: 'basic',
    text: 'To which production type do you assign your company?',
    options: [
      { text: 'One time production' },
      { text: 'Individual and small series production' },
      { text: 'Series production' },
      { text: 'Mass production' },
      { text: 'N/A', isNA: true },
    ],
  },
  {
    id: 11,
    type: 'basic',
    text: 'How far are you with your IT security solutions?',
    isMatrix: true,
    matrixHeader: 'Security Area',
    children: [
      {
        id: 1101,
        type: 'basic',
        text: 'Security of internal data storage',
        options: [
          { text: 'Solution Implemented' },
          { text: 'Solution in Work' },
          { text: 'Solution Planned' },
          { text: 'No Plans' },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 1102,
        type: 'basic',
        text: 'Security of cloud data storage',
        options: [
          { text: 'Solution Implemented' },
          { text: 'Solution in Work' },
          { text: 'Solution Planned' },
          { text: 'No Plans' },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 1103,
        type: 'basic',
        text: 'Security of data exchange with external partners/companies',
        options: [
          { text: 'Solution Implemented' },
          { text: 'Solution in Work' },
          { text: 'Solution Planned' },
          { text: 'No Plans' },
          { text: 'N/A', isNA: true },
        ],
      },
    ],
  },
  {
    id: 12,
    type: 'basic',
    text: 'How do you assess the skills and know-how of your employees in relation to Industry 4.0?',
    isMatrix: true,
    matrixHeader: 'Role',
    children: [
      {
        id: 121,
        type: 'basic',
        text: 'Managing Directors',
        options: [
          { text: 'Low' },
          { text: 'Sufficient' },
          { text: 'Average' },
          { text: 'Good' },
          { text: 'Very Good' },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 122,
        type: 'basic',
        text: 'Executives',
        options: [
          { text: 'Low' },
          { text: 'Sufficient' },
          { text: 'Average' },
          { text: 'Good' },
          { text: 'Very Good' },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 123,
        type: 'basic',
        text: 'Workers',
        options: [
          { text: 'Low' },
          { text: 'Sufficient' },
          { text: 'Average' },
          { text: 'Good' },
          { text: 'Very Good' },
          { text: 'N/A', isNA: true },
        ],
      },
    ],
  },
  {
    id: 1300,
    type: 'basic',
    text: 'Section 3 - Organization Digital Maturity',
    children: [
      {
        id: 1310,
        type: 'basic',
        text: 'Digital Strategy & Vision',
        children: [
          {
            id: 1311,
            type: 'basic',
            text: 'What best describes your organization strategy to digital transformation?',
            options: [
              {
                text: 'No articulated digital strategy in the organization',
                score: 1,
              },
              {
                text: 'Digital Strategy articulated but is not used by the business operations',
                score: 2,
              },
              {
                text: 'Digital Strategy articulated and is relevant and used by the business operations',
                score: 3,
              },
              {
                text: 'Digital Strategy is a dynamic and is business led and driven',
                score: 4,
              },
              {
                text: 'Digital Strategy is transformative and central to the future success of the organization',
                score: 5,
              },
              { text: 'N/A', isNA: true },
            ],
          },
        ],
      },
      {
        id: 1320,
        type: 'basic',
        text: 'Data & Analytics',
        children: [
          {
            id: 1321,
            type: 'basic',
            text: 'What best describes the data maturity in your organization?',
            options: [
              {
                text: 'Data is kept mostly in employee systems in spreadsheets and logs',
                score: 1,
              },
              {
                text: 'Transaction data from a siloed systems is in use in the organization',
                score: 2,
              },
              {
                text: 'Structured data from multiple internal systems are integrated and used within organization',
                score: 3,
              },
              {
                text: 'Real-time data sources like web data and IoT data is augmented to the existing data sources',
                score: 4,
              },
              {
                text: 'Organization procures trusted external data to augment and enrich its own datasets',
                score: 5,
              },
              { text: 'N/A', isNA: true },
            ],
          },
          {
            id: 1322,
            type: 'basic',
            text: 'What best describes the culture for data-driven decision making within your organization?',
            options: [
              {
                text: 'Decision makers rely on perceptions, historical decisions and non-validated beliefs.',
                score: 1,
              },
              {
                text: 'Decision makers recognize benefits of data analytics to support decision making but don’t leverage analytics consistently.',
                score: 2,
              },
              {
                text: 'Decision makers adopt data analytics for all decisions, including key investments and resource allocation.',
                score: 3,
              },
              {
                text: 'Decision makers leverage analytics across the organization to support business decisions.',
                score: 4,
              },
              {
                text: 'Decision makers search for new ways to use advanced analytics to support business decisions.',
                score: 5,
              },
              { text: 'N/A', isNA: true },
            ],
          },
        ],
      },
      {
        id: 1330,
        type: 'basic',
        text: 'Organization & Skills',
        children: [
          {
            id: 1331,
            type: 'basic',
            text: 'Who drives digital transformation agenda in the organization?',
            options: [
              {
                text: 'There is no single ownership for digital transformation within organization. It is ad-hoc',
                score: 1,
              },
              {
                text: 'IT team drives the digital transformation agenda',
                score: 2,
              },
              {
                text: 'Digital Transformation is owned and driven by respective departments',
                score: 3,
              },
              {
                text: 'CEO has an additional responsibility of driving the digital transformation in the organization',
                score: 4,
              },
              {
                text: 'CDO, with dedicated P/L,reporting to the board, drives the digital transformation agenda',
                score: 5,
              },
              { text: 'N/A', isNA: true },
            ],
          },
          {
            id: 1332,
            type: 'basic',
            text: 'How best describes your approach to creating the digital talent pool within the organization?',
            options: [
              {
                text: "We don't have a strategy in place to build new talent pool in the organization. Few skills attached to the functions",
                score: 1,
              },
              {
                text: 'Pockets of skills with organization. Not connected and no skill management',
                score: 2,
              },
              {
                text: 'Digital skills recognized as a key business differentitor and some hiring and training programs launched',
                score: 3,
              },
              {
                text: 'Company-wide initiative to train and upskill existing resources and deploy them on new projects',
                score: 4,
              },
              {
                text: 'Future business strategy is build around digital capabilities. Specific role based training and upskilling program in place across all layers and functions of the company',
                score: 5,
              },
              { text: 'N/A', isNA: true },
            ],
          },
        ],
      },
      {
        id: 1340,
        type: 'basic',
        text: 'Process & Technology',
        children: [
          {
            id: 1341,
            type: 'basic',
            text: 'How are processes defined within the organization?',
            options: [
              {
                text: 'Processes are manual and ad-hoc. There is little or no process documentation or control',
                score: 1,
              },
              {
                text: 'Processes are partly digitized but there is lack of control and adoption resulting in high process variations',
                score: 2,
              },
              {
                text: 'Processes are standardized across business units and there are controls to ensure high adoption and low process variations',
                score: 3,
              },
              {
                text: 'E2E processes are digitized and standardized with clear process ownership and metrics defined',
                score: 4,
              },
              {
                text: 'Organization is continuously looking for ways to improve business processes with a clear focus on evolving customer needs',
                score: 5,
              },
              { text: 'N/A', isNA: true },
            ],
          },
          {
            id: 1342,
            type: 'basic',
            text: 'What is the organization approach to digital technology acquisition?',
            options: [
              {
                text: 'Organization does not believe digital technology is a business differentiator and does not make investments beyond basic spreadsheets',
                score: 1,
              },
              {
                text: 'Organization considers technology as a cost function and makes investment based on core - financial, regulatory or specific customer requirements',
                score: 2,
              },
              {
                text: 'Organization makes some technology investments outside of core requirements but those are internally focused and made for improving process efficiencies',
                score: 3,
              },
              {
                text: 'There is an understanding that technology is a key business enabler and decisions on technology is both external and internal facing. A customer metric based business case is required for investment decision',
                score: 4,
              },
              {
                text: 'Company has adopted a forward looking platform approach to technology. The technology backbone supports rapid development and deployment of products and services',
                score: 5,
              },
              { text: 'N/A', isNA: true },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 19,
    type: 'basic',
    text: 'What is the adoption of the following digital technologies on Shopfloor',
    isMatrix: true,
    matrixHeader: 'Technology',
    children: [
      {
        id: 191,
        type: 'basic',
        text: 'Connected Machine - IOT',
        options: [
          { text: 'Not Initiated', score: 1 },
          { text: 'Demo Completed', score: 2 },
          { text: 'Actively Exploring', score: 3 },
          { text: 'Pilot Done', score: 4 },
          { text: 'In Production', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 192,
        type: 'basic',
        text: 'Condition Based Monitoring',
        options: [
          { text: 'Not Initiated', score: 1 },
          { text: 'Demo Completed', score: 2 },
          { text: 'Actively Exploring', score: 3 },
          { text: 'Pilot Done', score: 4 },
          { text: 'In Production', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 193,
        type: 'basic',
        text: 'Andon Boards',
        options: [
          { text: 'Not Initiated', score: 1 },
          { text: 'Demo Completed', score: 2 },
          { text: 'Actively Exploring', score: 3 },
          { text: 'Pilot Done', score: 4 },
          { text: 'In Production', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 194,
        type: 'basic',
        text: 'Role Based Dashboards',
        options: [
          { text: 'Not Initiated', score: 1 },
          { text: 'Demo Completed', score: 2 },
          { text: 'Actively Exploring', score: 3 },
          { text: 'Pilot Done', score: 4 },
          { text: 'In Production', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 195,
        type: 'basic',
        text: 'SCADA and PLC Systems',
        options: [
          { text: 'Not Initiated', score: 1 },
          { text: 'Demo Completed', score: 2 },
          { text: 'Actively Exploring', score: 3 },
          { text: 'Pilot Done', score: 4 },
          { text: 'In Production', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 196,
        type: 'basic',
        text: 'Bar-Code/ QR Code/BLE etc. for traceability',
        options: [
          { text: 'Not Initiated', score: 1 },
          { text: 'Demo Completed', score: 2 },
          { text: 'Actively Exploring', score: 3 },
          { text: 'Pilot Done', score: 4 },
          { text: 'In Production', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 197,
        type: 'basic',
        text: 'Robotics & Co-Bots',
        options: [
          { text: 'Not Initiated', score: 1 },
          { text: 'Demo Completed', score: 2 },
          { text: 'Actively Exploring', score: 3 },
          { text: 'Pilot Done', score: 4 },
          { text: 'In Production', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 198,
        type: 'basic',
        text: "AGV's",
        options: [
          { text: 'Not Initiated', score: 1 },
          { text: 'Demo Completed', score: 2 },
          { text: 'Actively Exploring', score: 3 },
          { text: 'Pilot Done', score: 4 },
          { text: 'In Production', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 199,
        type: 'basic',
        text: 'MES',
        options: [
          { text: 'Not Initiated', score: 1 },
          { text: 'Demo Completed', score: 2 },
          { text: 'Actively Exploring', score: 3 },
          { text: 'Pilot Done', score: 4 },
          { text: 'In Production', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 1910,
        type: 'basic',
        text: 'Utility Management',
        options: [
          { text: 'Not Initiated', score: 1 },
          { text: 'Demo Completed', score: 2 },
          { text: 'Actively Exploring', score: 3 },
          { text: 'Pilot Done', score: 4 },
          { text: 'In Production', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 1911,
        type: 'basic',
        text: 'Spares Management',
        options: [
          { text: 'Not Initiated', score: 1 },
          { text: 'Demo Completed', score: 2 },
          { text: 'Actively Exploring', score: 3 },
          { text: 'Pilot Done', score: 4 },
          { text: 'In Production', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 1912,
        type: 'basic',
        text: 'Tool Life Management',
        options: [
          { text: 'Not Initiated', score: 1 },
          { text: 'Demo Completed', score: 2 },
          { text: 'Actively Exploring', score: 3 },
          { text: 'Pilot Done', score: 4 },
          { text: 'In Production', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 1913,
        type: 'basic',
        text: 'AR/VR',
        options: [
          { text: 'Not Initiated', score: 1 },
          { text: 'Demo Completed', score: 2 },
          { text: 'Actively Exploring', score: 3 },
          { text: 'Pilot Done', score: 4 },
          { text: 'In Production', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 1914,
        type: 'basic',
        text: 'Others (Please mention)',
        options: [
          { text: 'Not Initiated', score: 1 },
          { text: 'Demo Completed', score: 2 },
          { text: 'Actively Exploring', score: 3 },
          { text: 'Pilot Done', score: 4 },
          { text: 'In Production', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
    ],
  },
  {
    id: 20,
    type: 'basic',
    text: 'What is the maturity of your enterprise systems?',
    isMatrix: true,
    matrixHeader: 'System',
    children: [
      {
        id: 2001,
        type: 'basic',
        text: 'Enterprise Resource Planning',
        options: [
          { text: 'Not in Use', score: 0 },
          { text: 'Low Maturity', score: 1 },
          { text: 'Medium Maturity', score: 3 },
          { text: 'High Maturity', score: 4 },
          { text: 'Maturity with Benefits', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 2002,
        type: 'basic',
        text: 'Customer Relationship Management',
        options: [
          { text: 'Not in Use', score: 0 },
          { text: 'Low Maturity', score: 1 },
          { text: 'Medium Maturity', score: 3 },
          { text: 'High Maturity', score: 4 },
          { text: 'Maturity with Benefits', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 2003,
        type: 'basic',
        text: 'Sales Platform',
        options: [
          { text: 'Not in Use', score: 0 },
          { text: 'Low Maturity', score: 1 },
          { text: 'Medium Maturity', score: 3 },
          { text: 'High Maturity', score: 4 },
          { text: 'Maturity with Benefits', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 2004,
        type: 'basic',
        text: 'Dealer Management System',
        options: [
          { text: 'Not in Use', score: 0 },
          { text: 'Low Maturity', score: 1 },
          { text: 'Medium Maturity', score: 3 },
          { text: 'High Maturity', score: 4 },
          { text: 'Maturity with Benefits', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 2005,
        type: 'basic',
        text: 'CAD/CAM',
        options: [
          { text: 'Not in Use', score: 0 },
          { text: 'Low Maturity', score: 1 },
          { text: 'Medium Maturity', score: 3 },
          { text: 'High Maturity', score: 4 },
          { text: 'Maturity with Benefits', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 2006,
        type: 'basic',
        text: 'Product Lifecycle Management',
        options: [
          { text: 'Not in Use', score: 0 },
          { text: 'Low Maturity', score: 1 },
          { text: 'Medium Maturity', score: 3 },
          { text: 'High Maturity', score: 4 },
          { text: 'Maturity with Benefits', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 2007,
        type: 'basic',
        text: 'Supplier Relationship Management',
        options: [
          { text: 'Not in Use', score: 0 },
          { text: 'Low Maturity', score: 1 },
          { text: 'Medium Maturity', score: 3 },
          { text: 'High Maturity', score: 4 },
          { text: 'Maturity with Benefits', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 2008,
        type: 'basic',
        text: 'Human Resource Management Systems',
        options: [
          { text: 'Not in Use', score: 0 },
          { text: 'Low Maturity', score: 1 },
          { text: 'Medium Maturity', score: 3 },
          { text: 'High Maturity', score: 4 },
          { text: 'Maturity with Benefits', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 2009,
        type: 'basic',
        text: 'Warehouse Management System',
        options: [
          { text: 'Not in Use', score: 0 },
          { text: 'Low Maturity', score: 1 },
          { text: 'Medium Maturity', score: 3 },
          { text: 'High Maturity', score: 4 },
          { text: 'Maturity with Benefits', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 2010,
        type: 'basic',
        text: 'E-Shop floor management',
        options: [
          { text: 'Not in Use', score: 0 },
          { text: 'Low Maturity', score: 1 },
          { text: 'Medium Maturity', score: 3 },
          { text: 'High Maturity', score: 4 },
          { text: 'Maturity with Benefits', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 2011,
        type: 'basic',
        text: 'Data Lake/Data Platform',
        options: [
          { text: 'Not in Use', score: 0 },
          { text: 'Low Maturity', score: 1 },
          { text: 'Medium Maturity', score: 3 },
          { text: 'High Maturity', score: 4 },
          { text: 'Maturity with Benefits', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 2012,
        type: 'basic',
        text: 'Enterprise AI /Analytics Platform',
        options: [
          { text: 'Not in Use', score: 0 },
          { text: 'Low Maturity', score: 1 },
          { text: 'Medium Maturity', score: 3 },
          { text: 'High Maturity', score: 4 },
          { text: 'Maturity with Benefits', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 2013,
        type: 'basic',
        text: 'Master data management (MDM)',
        options: [
          { text: 'Not in Use', score: 0 },
          { text: 'Low Maturity', score: 1 },
          { text: 'Medium Maturity', score: 3 },
          { text: 'High Maturity', score: 4 },
          { text: 'Maturity with Benefits', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
      {
        id: 2014,
        type: 'basic',
        text: 'Others ( Please Mention)',
        options: [
          { text: 'Not in Use', score: 0 },
          { text: 'Low Maturity', score: 1 },
          { text: 'Medium Maturity', score: 3 },
          { text: 'High Maturity', score: 4 },
          { text: 'Maturity with Benefits', score: 5 },
          { text: 'N/A', isNA: true },
        ],
      },
    ],
  },
];
