# Generated by Django 6.0.3 on 2026-04-08 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('functional', 'Functional'), ('sector', 'Sector')], max_length=20)),
                ('sector_code', models.CharField(blank=True, max_length=50, null=True)),
                ('definition', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_catalogs_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_catalogs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'sector_code'],
                'unique_together': {('category', 'sector_code')},
            },
        ),
    ]
